name: Prices snapshot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"  # Cada 5 minutos

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Run fetch-prices.js
        run: node scripts/fetch-prices.js
