name: Prices snapshot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *" # cada 5 minutos

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Ejecutar script
        run: node scripts/fetch-prices.js

      - name: Commit y push de snapshot
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/snapshot.json
          git commit -m "Update snapshot"
          git push
