name: Prices snapshot
on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"
  repository_dispatch:
    types: [manual-siteops-dispatch, siteops-deploy]  # ← añade esto

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Run fetch script
        run: node scripts/fetch-prices.js
      - name: Commit snapshot
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/snapshot.json
          git commit -m "snapshot $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "no changes"
          git push || true
